config/routes.rb
Newdad::Application.routes.draw do

  root :to => 'sessions#new'

  match '/about', to: 'pages#about'
  match '/contact', to: 'pages#contact'
  match '/signup', to: 'users#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/eventi', to: 'pages#eventi'
  match '/muro_sfogo', to: 'pages#wall_outburst'

  resources :users do
    member do
      get :following, :followers, :messages, :friends, :my_questions, :informazioni_profilo
    end

    collection do
      get :search
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :messages, only: [:new, :create, :destroy]

  resources :questions do

    collection do
      get :home, :search
    end
  end

  resources :like_questions, only: [:create, :destroy]
  resources :categories
  resources :answers, only: [:create, :destroy]
  resources :age_groups, only: [:show]
  resources :like_answers, only: [:create, :destroy]

end

app/models/question.rb
class Question < ActiveRecord::Base

  #variabili accessibili dall'utente
  attr_accessible :age_group_id, :content, :title, :category_id

  #una domanda appartiene ad un utente, ad una categoria e ad uns fascia d'età
  belongs_to :user
  belongs_to :category
  belongs_to :age_group

  #TO_DO: da mettere in ordine alfabetico
  #ordinamento di default in base alla data di creazione
  default_scope order:'questions.created_at DESC'

  #una domanda ha molte risposte
  has_many :answers, dependent: :destroy

  #una domanda può avere molti utenti a cui piace
  has_many :like_questions, foreign_key: 'question_id'
  has_many :users_like, through: :like_questions,  source: :user

  #validazioni dei campi: tutti sono obbligatori
  validates :user_id, presence: true
  validates :title, presence: true, length: {maximum: 100}
  validates :category_id, presence: true, :numericality => true
  validates :age_group_id, presence: true, :numericality => true
  validates :content, presence:true, length: {maximum: 800}

  #cerca gli id del mio utente e dei miei followed
  def self.from_users_followed_by(user)
    followed_user_ids = 'SELECT followed_id FROM relationships WHERE follower_id = :user_id'
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", user_id: user.id)
  end

  #metodo per la ricerca tramite la categora e/o la fascia d'età
  def self.search(category_id, age_group_id)
    if category_id && age_group_id
      if category_id.blank? && age_group_id.blank?
       self
      elsif category_id.blank?
        where('age_group_id = ?', "#{age_group_id}")
      elsif age_group_id.blank?
        where('category_id = ?', "#{category_id}")
      else
        where(['category_id = ? and age_group_id = ?', "#{category_id}", "#{age_group_id}"])
      end
      else
      scoped # return an empty result set
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_filter :signed_in_user
  before_filter :correct_user, only: :destroy

  def new
    @question = Question.new

    @category = Category.where("waiting = 'f' and accepted = 't'")
    @age_groups = AgeGroup.all

  end

  def show
    @question = Question.find_by_id(params[:id])
    @category = Category.where("waiting = 'f' and accepted = 't'")
    @age_group = AgeGroup.all

    @answer = current_user.answers.build if signed_in?
    @like_answer = current_user.like_answers.build if signed_in?
    @response_items = @question.answers.paginate(page: params[:page])

    @like = 0
    @questions2 = current_user.questions.all
    @q_like = LikeQuestion.all

    @q_like.each { |q_like| @questions2.each{ |questions2| if questions2.id == q_like.question_id
                                                             @like = @like+1
                                                           end}}
    @answer2 = current_user.answers.all
    @a_like = LikeAnswer.all
    @a_like.each{ |a_like| @answer2.each{ |answer2| if answer2.id == a_like.answer_id
                                                @like = @like+1
                                                end} }
  end

  def create
    @question = current_user.questions.build(params[:question])

    if params[:preview_button] || !@question.save
      @query_items = []
      render 'questions/new'

    else
      flash[:success] = 'Domanda inserita con successo'
      redirect_to questions_path
    end
  end

 #seleziono la domanda corrente e le risposte di quella domanda
  #cancello prima tutte le risposte e poi la domanda
  def destroy
    @question = Question.find(params[:id])
    @answers = @question.answers.all

    @answers.each { @question.answers.destroy}
    @question.destroy

    flash[:success] = 'Domanda e relative risposte cancellate!'

    redirect_to questions_url
  end


  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(params[:question])
      flash[:success] = 'Domanda aggiornata'
      redirect_to question_path
    else
      render 'edit'
    end

  end

  def index
    @questions = Question.paginate(page: params[:page])
    @category = Category.where("waiting = 'f' and accepted = 't'")
    @age_group = AgeGroup.all

    @like = 0
    @questions2 = current_user.questions.all
    @q_like = LikeQuestion.all

    @q_like.each { |q_like| @questions2.each{ |questions2| if questions2.id == q_like.question_id
                                                                  @like = @like+1
                                                           end}}

    @answer2 = current_user.answers.all
    @a_like = LikeAnswer.all
    @a_like.each{ |a_like| @answer2.each{ |answer2| if answer2.id == a_like.answer_id
                                                      @like = @like+1
                                                    end} }
  end


  def home
    @questions = Question.all(limit: 10)
    @category = Category.where("waiting = 'f' and accepted = 't'")
    @age_group = AgeGroup.all

    @like = 0
    @questions2 = current_user.questions.all
    @q_like = LikeQuestion.all

    @q_like.each { |q_like| @questions2.each{ |questions2| if questions2.id == q_like.question_id
                                                             @like = @like+1
                                                           end}}

    @answer2 = current_user.answers.all
    @a_like = LikeAnswer.all
    @a_like.each{ |a_like| @answer2.each{ |answer2| if answer2.id == a_like.answer_id
                                                      @like = @like+1
                                                    end} }
  end


  def search
    @questions = Question.search(params[:category_id], params[:age_group_id]).paginate(page: params[:page])

    @category = Category.where("waiting = 'f' and accepted = 't'")
    @age_group = AgeGroup.all

    @like = 0
    @questions2 = current_user.questions.all
    @q_like = LikeQuestion.all

    @q_like.each { |q_like| @questions2.each{ |questions2| if questions2.id == q_like.question_id
                                                             @like = @like+1
                                                           end}}

    @answer2 = current_user.answers.all
    @a_like = LikeAnswer.all
    @a_like.each{ |a_like| @answer2.each{ |answer2| if answer2.id == a_like.answer_id
                                                      @like = @like+1
                                                    end} }
  end



  private

  def correct_user
    @question = current_user.questions.find_by_id(params[:id])
    redirect_to root_url if @question.nil?
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper

  # data una domanda estrae il nome della categoria a cui appartiene
  def category_name(question)
    category_id = question.category_id
    category = Category.find_by_id(category_id)
    @category_name = category.title
  end

  # data una domanda estrae il nome della fascia d'età a cui appartiene
  def age_groups_name(question)
    age_group_id = question.age_group_id
    age_group = AgeGroup.find_by_id(age_group_id)
    @age_group_name = age_group.name
  end

end

app/views/questions/_age_group.html.erb

<li id="<%= age_group.id %>">
  <%= link_to age_group.name, age_group %>
</li>

app/views/questions/_answer_form.html.erb

<%= form_for(@answer) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="row">

    <div class="field span7">
      <%= f.text_area :content, placeholder: 'Cosa ne pensi?' %>
      <%= f.hidden_field :question_id, value: @question.id %>
    </div>

    <div class="span2">
      <%= f.submit 'Rispondi', class: 'btn btn-info' %>
    </div>

  </div>
<% end %>









app/views/questions/_category.html.erb

<li id="<%= category.id %>">
  <%= link_to category.title, category %>
</li>

app/views/questions/_like_question_form.html.erb

<% unless current_user?(@user) %>
  <div id="like_question_form">

    <% if current_user.like_questions?(@question) %>
      <%= render 'dont_like_question' %>
    <% else %>
      <%= render 'like_question' %>
    <% end %>

  </div>
<% end %>

app/views/questions/_list_age_groups.html.erb

<div class="navbar-inner-fixed-top navbar-inverse">

  <div class="navbar-inner">
    <div class="container">

      <ul class="nav pull">
        <% if @age_group.any? %>
          <li><%= render partial: 'questions/age_group', collection: @age_group %></li>
        <% end %>
      </ul>

    </div>
  </div>
</div>


app/views/questions/_list_category.html.erb

<div class="navbar-inner-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">

      <% if @category.any? %>
        <li><%= render partial: 'questions/category', collection: @category %></li>
      <% end %>

    </div>
  </div>
</div>


app/views/questions/_menu.html.erb

<div class="navbar-inner-fixed-top navbar-inverse">

  <div class="row offset1">

    <div class="span3 navbar-inner center">
      <ul class="nav nav-list">
        <li><%= link_to 'Tutte le domande', questions_path %></li>
        <li><%= link_to 'Mie domande', my_questions_user_path(current_user) %></li>
      </ul>
    </div>

    <div class="span2">
      <%= link_to 'Nuova Domanda', new_question_path, role: 'button', class: 'btn btn-info' %>
    </div>

    <div class="span2">
      <% if current_user.admin? || @like > 2 %>
        <%= link_to 'Nuova Categoria', new_category_path, role: 'button', class: 'btn btn-info' %>
      <% end %>
    </div>

    <!-- popup nuova categoria -->
    <div class="span1">
      <div class="panel">
        <a href="#join_form" id="join_pop">?</a>
      </div>
    </div>

    <a href="#x" class="overlay" id="join_form"></a>

    <div class="popup">
      <h2>Creazione nuova categoria</h2>
      <p class="center">Potrai creare una nuova categoria solo quando</p>
      <p class="center">otterrai almeno 2 "mi piace" da parte degli altri utenti.</p>
      <a class="close" href="#close"></a>
    </div>

    <div class="span2">
      <%# blocco per sapere quanti mi piace gli altri utenti hanno dato alle domande che ha scritto l'utente loggato %>
      <%= image_tag("mi_piace.png") %><p class="mi_piace">Mi piace: <%=  @like %></p>
    </div>

  </div>
</div>

app/views/questions/_question.html.erb

<li>

 <%= link_to gravatar_for (question.user), question.user %>
 <h5 class="nome"><%= link_to question.user.name, question.user %></h5>
 <span><%= link_to question.title, question %></span>
 <span class="timestamp"> Domanda creata <%= time_ago_in_words(question.created_at)%> fa</span>

</li>





app/views/questions/edit.html.erb
<% provide :title, 'Modifica domanda' %>

<% if signed_in? %>
  <div class="row">
    <div class="span6 offset2">

      <h1 >Modifica domanda</h1>

      <%= form_for @question do |f| %>

        <%= render 'shared/error_messages', object:f.object %>
        <p>Titolo:</p>
        <%= f.text_field :title %>

        <p>Categoria:</p>
        <%= f.collection_select(:category_id, Category.all, :id, :title) %>

        <p>Fascia d'età:</p>
        <%= f.collection_select(:age_group_id, AgeGroup.all, :id, :name) %>

        <p>Descrizione:</p>
        <%= f.text_area :content %>

        <div class="center">
          <%= link_to 'Annulla', :back, class: 'btn btn-info' %>
          <%= f.submit'Modifica domanda', class:'btn btn-info' %>
        </div>

      <% end %>

    </div>
  </div>

<% else %>
  <p>Login non effettuato. <%= link_to 'Home', root_path %> </p>
<% end %>


app/views/questions/home.html.erb
<% provide :title %>

<% if signed_in?%>

  <div class="row">
    <%= render 'questions/menu' %>
  </div>

  <div class="row">
    <%= render 'questions/search_form' %>
  </div>

  <h1>Le ultime dieci domande</h1>

  <ul class="users">
    <%= render @questions %>
  </ul>

<% else %>
  <p>Login non effettuato. <%= link_to 'Home', root_path %> </p>
<% end %>

app/views/questions/index.html.erb
<% provide :title, 'Domande' %>

<% if signed_in?%>

  <div class="row">
    <%= render 'questions/menu' %>
  </div>

  <div class="row">
    <%= render 'questions/search_form' %>
  </div>

  <h1>Tutte le domande</h1>

  <ul class="users">
    <%= render @questions %>
  </ul>

  <%= will_paginate%>

<% else %>
  <p>Login non effettuato. <%= link_to 'Home', root_path %> </p>
<% end %>

app/views/questions/my_questions.html.erb
<% provide :title %>

    <div class="row">

      <%= render 'list_category' %>


      <div class="span8">

        <% if @user.questions.any? %>
            <h3>Mie domande (<%= @user.questions.count %>)</h3>
            <ol class="questions">
              <%= render @questions %>
            </ol>
            <% will_paginate @questions %>
        <% end %>
      </div>

    </div>

app/views/questions/new.html.erb
<% provide :title, 'Nuova domanda' %>

<% if signed_in?%>

  <h1 >Nuova domanda</h1>

  <%= form_for @question do |f| %>

    <% if params[:preview_button]%>
    <%# se si schiaccia il bottone anteprima si fa vedere come si presenta la domanda una volta salvata %>

      <%= render 'shared/error_messages', object:f.object %>
      <div class="anteprimadomanda center">
        <p>Titolo: <%= @question.title %></p>
        <p>Categoria: <%= category_name(@question) %></p>
        <p>Fascia d'età: <%= age_groups_name(@question) %></p>
        <p>Descrizione: <%= @question.content %></p>
      </div>

    <% end %>

    <div class="row">
      <div class="span6 offset3">
        <%= render 'shared/error_messages', object:f.object %>

        <p>Titolo:</p>
        <%=  f.text_field :title %>

        <p>Categoria:</p>
        <%= f.collection_select(:category_id, Category.all, :id, :title) %>

        <p>Fascia d'età</p>
        <%= f.collection_select(:age_group_id, AgeGroup.all, :id, :name) %>

        <p>Descrizione:</p>
        <%=  f.text_area :content %>
      </div>
    </div>

    <div class="center">
      <%= link_to 'Annulla', :back, role: 'button', class: 'btn btn-info' %>
      <%= f.submit 'Crea nuova domanda',class: 'btn btn-info' %>
      <%= f.submit 'Anteprima', :name => 'preview_button',class: 'btn btn-info' %>
    </div>
  <% end %>

<% else %>
  <p>Login non effettuato. <%= link_to 'Home', root_path %> </p>
<% end %>

app/views/questions/search.html.erb
<% provide :title, 'Risultati ricerca' %>

<% if signed_in? %>

  <div class="row">
    <%= render 'questions/menu' %>
  </div>

  <div class="row">
    <%= render 'questions/search_form' %>
  </div>

  <h1><%= page_entries_info @questions %></h1>
  <ul class="users">
    <%= render @questions %>
  </ul>

  <%= will_paginate %>

<% else %>
    <p>Login non effettuato. <%= link_to 'Home', root_path %> </p>
<% end %>