config/routes.rb
Newdad::Application.routes.draw do

  root :to => 'sessions#new'

  match '/about', to: 'pages#about'
  match '/contact', to: 'pages#contact'
  match '/signup', to: 'users#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/eventi', to: 'pages#eventi'
  match '/muro_sfogo', to: 'pages#wall_outburst'

  resources :users do
    member do
      get :following, :followers, :messages, :friends, :my_questions, :informazioni_profilo
    end

    collection do
      get :search
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :messages, only: [:new, :create, :destroy]

  resources :questions do

    collection do
      get :home, :search
    end
  end

  resources :like_questions, only: [:create, :destroy]
  resources :categories
  resources :answers, only: [:create, :destroy]
  resources :age_groups, only: [:show]
  resources :like_answers, only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :email, :name, :password, :password_confirmation, :n_children, :city, :description, :em_situation, :employment, :birthday

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  has_secure_password
  has_private_messages

  # un utente scrive molte domande, molte risposte, molti post e ha molti figli; può eliminare post, domande e risposte
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :childrens

  #un utente può aver aggiunto molte categorie
  has_many :categories

  #un utente segue molti utenti attraverso la tabella 'relationship'
  has_many :relationships, foreign_key: 'follower_id', dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed

  #un utente è seguito da molti utenti tramite la tabella 'reverse relationship'
  has_many :reverse_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :reverse_relationships

  #ad un utente piace una domanda tramite la tabella like_questions
  has_many :like_questions, foreign_key: 'user_id', dependent: :destroy
  has_many :like_q, through: :like_questions, source: :question

  #ad un utente piace una domanda tramite la tabella like_questions
  has_many :like_answers, foreign_key: 'user_id', dependent: :destroy
  has_many :like_a, through: :like_answers, source: :answer

  #campi obbligatori --> validazioni
  validates :name, presence:true, length: {maximum: 50}
  validates :email, presence:true, uniqueness: { case_sensitive: false }, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/, :on => :create }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  validates :n_children, presence: true, :numericality => true

  #campi non obbligatori --> validazioni
  validates :city, length: { maximum: 50 }
  validates :description, length: { maximum: 450}
  validates :em_situation, length:{ maximum: 50 }
  validates :employment, length:{ maximum: 50}

  # metodi per i followers e i followed
  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end

  #metodi per i "Mi piace/Non mi piace più" per le domande
  def like_questions?(question)
    like_questions.find_by_question_id(question.id)
  end

  def like_questions!(question)
    like_questions.create!(question_id: question.id)
  end

  def dont_like_questions!(question)
    like_questions.find_by_question_id(question.id).destroy
  end

  #metodi per i "Mi piace/Non mi piace più" per le risposte
  def like_answers?(answer)
    like_answers.find_by_answer_id(answer.id)
  end

  def like_answers!(answer)
    like_answers.create!(answer_id: answer.id)
  end

  def dont_like_answers!(answer)
    like_answers.find_by_answer_id(answer.id).destroy
  end

  #metodo: prende i post con user_id uguale a quelli trovati dal metodo from_users_followed_by (mio e miei followed)
  def feed
    Post.from_users_followed_by(self)
  end

  #metodo: prende le domande con user_id uguale a quelli trovati dal metodo from_users_followed_by (mio e miei followed)
  def query
    Question.from_users_followed_by(self)
  end

  #metodo: prende le risposte con user_id uguale a quelli trovati dal metodo from_users_followed_by (mio e miei followed)
  def answer
    Answer.from_users_followed_by(self)
  end

  #metodo per la ricerca tramite il nome degli utenti (ricerca in alto)
  def self.search(user_name)
    if user_name
      where('name LIKE ?', "%#{user_name}%")
    else
      scoped # return an empty result set
    end
  end


  #metodi privati
  private

  #creazione remeber_token per la sessione
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :signed_in_user, only: [:edit, :update, :index, :destroy, :messages]
  before_filter :correct_user, only: [:edit, :update, :messages]
  before_filter :admin_user, only: :destroy

  def show
    @user = User.find(params[:id])
    @category = Category.where("waiting = 't' and accepted = 'f'")
    @posts = @user.posts.paginate(page: params[:page])
    @query_items = @user.questions.paginate(page: params[:page])
    @answers = @user.answers.paginate(page: params[:page])
    @answer_items = @user.answers.paginate(page: params[:page]) if signed_in?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      flash[:success] = 'Benvenuto in New Dad'
      sign_in @user
      redirect_to root_path
    else
      render 'new'
    end
  end


  def edit
  end

  def update
    if @user.update_attributes(params[:user])

      flash[:success] = 'Profilo aggiornato'
      sign_in @user
      redirect_to informazioni_profilo_user_path(current_user)
    else

      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'Utente cancellato!'
    redirect_to users_url
  end

  def following
    @title = 'Following'
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = 'Followers'
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  def friends
    @title = 'Amici'
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    @users2 = @user.followed_users.paginate(page: params[:page])
    render 'friends'
  end

  def search
    @users = User.search(params[:search]).paginate(page: params[:page])
  end

  def messages
    @user = User.find(params[:id])
    @messages = @user.received_messages.paginate(page: params[:page])
  end

  def my_questions
    @user = User.find(params[:id])
    @questions = @user.questions.paginate(page: params[:page])
    @category = Category.where("waiting = 'f' and accepted = 't'")
    @age_group = AgeGroup.all

    @like = 0
    @questions2 = current_user.questions.all
    @q_like = LikeQuestion.all

    @q_like.each { |q_like| @questions2.each{ |questions2| if questions2.id == q_like.question_id
                                                             @like = @like+1
                                                           end}}

    @answer2 = current_user.answers.all
    @a_like = LikeAnswer.all
    @a_like.each{ |a_like| @answer2.each{ |answer2| if answer2.id == a_like.answer_id
                                                      @like = @like+1
                                                    end} }
  end

  def informazioni_profilo
    @user = User.find(params[:id])
    @children = @user.childrens.all
  end


  private

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user) # the current_user?(user) method is defined in the SessionsHelper
  end

  def admin_user
    redirect_to root_path unless current_user.admin?
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options [:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=wavatar"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit 'Follow', class: 'btn btn-info' %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_menu_profilo.html.erb
<div class="navbar-inner-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">

      <ul class="nav nav-list">
        <li><%= link_to "Azioni", current_user %></li>
        <li><%= link_to "Informazioni", informazioni_profilo_user_path(current_user) %></li>
        <li><%= link_to "Amici", friends_user_path(current_user) %></li>
      </ul>

    </div>
  </div>
</div>

app/views/users/_search_form.html.erb

<%= form_tag search_users_path, method: 'get', class: 'navbar-search pull-left' do %>
   <%= text_field_tag :search, params[:search], class: 'search-query', placeholder: 'Ricerca' %>
<% end %>

app/views/users/_user.html.erb

<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>

  <% if current_user.admin? && !current_user?(user) %>
    <%= link_to 'Cancella', user, class:'btn btn-info btn-small', method: :delete, data: { confirm: 'Sei sicuro?' } %>
  <% end %>

</li>

app/views/users/amici.html.erb
<% provide(:title, @title) %>

<%= render 'users/menu_profilo' %>

<div class="row">
  <aside class="span4">
    <%= render 'shared/user_info_small'%>

  </aside>

  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
        <ul class="users">
          <h3>Followers</h3>
          <%= render @users %>
        </ul>
        <ul class="users">
          <h3>Following</h3>
          <%= render @users2 %>
        </ul>
        <%= will_paginate %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide :title, 'Modifica profilo' %>
<% if signed_in? %>
  <div class="row">
    <div class="span10">
      <div class="row">

        <div class="span4">
          <aside>
            <%= render 'shared/user_info_small' %>
          </aside>
          <%=  render 'users/menu_profilo' %>
        </div>

        <div class="span6">
          <h1>Modifica il tuo profilo</h1>

          <%= form_for(@user) do |f| %>

            <%= render 'shared/error_messages', object:f.object %>

            <%= f.label :name, 'Nome' %>
            <%= f.text_field :name %>

            <%= f.label :email %>
            <%= f.text_field :email %>

            <%= f.label :password %>
            <%= f.password_field :password %>

            <%= f.label :password_confirmation, 'Conferma password' %>
            <%= f.password_field :password_confirmation %>

            <%= f.label :n_children, 'Numero di figli'%>
            <%= f.text_field :n_children %>

            <%= f.label :birthday, 'Compleanno' %>
            <%= f.date_select :birthday, :include_blank => true %>

            <%= f.label :city, 'Dove abiti'%>
            <%= f.text_field :city %>

            <%= f.label :em_situation,'Situazione sentimentale'%>
            <%= f.select :em_situation, ['Single', 'Sposato', 'Separato', 'Divorziato', 'Convivente'], :include_blank => true %>

            <%= f.label :employment, 'Lavoro'%>
            <%= f.text_field :employment %>

            <%= f.label :description, 'Breve descrizione personale'%>
            <%= f.text_area :description %>

            <%= link_to 'Annulla', current_user, role: 'button', class: 'btn btn-info'  %>
            <%= f.submit 'Salva le modifiche', class: 'btn btn-info' %>

          <% end %>

          <%= gravatar_for @user %>
          <a href="http://gravatar.com/emails"><br/>Cambia la tua immagine</a>
        </div>
      </div>
    </div>
  </div>

<% else %>
    <p>Login non effettuato. <%= link_to 'Home', root_path %> </p>
<% end %>

app/views/users/friends.html.erb
<% provide(:title, @title) %>

<% if signed_in? %>

  <div class="row">

    <div class="span4">
      <aside>
        <%= render 'shared/user_info_small' %>
      </aside>

      <%=  render 'users/menu_profilo' %>
    </div>

    <h1><%= @title %></h1>

    <div class="span4">
      <% if @users.any? %>
        <ul class="users">
          <h3>Followers</h3>
          <%= render @users %>
        </ul>
      <% end %>
    </div>

    <div class="span4">
      <% if @users2.any? %>
        <ul class="users">
          <h3>Following</h3>
          <h5 class="nome"><%= render @users2 %> </h5>
        </ul>
        <%= will_paginate @users2%>
      <% end %>
    </div>

  </div>

<% else %>
  <p>Login non effettuato. <%= link_to 'Home', root_path %> </p>
<% end %>

app/views/users/index.html.erb
<% provide :title, 'Utenti' %>

<% if signed_in? %>

  <h1>Tutti gli utenti</h1>

  <div class="offset3">

    <ul class="users">
      <%= render @users %>
    </ul>
    <%= will_paginate %>

  </div>

<% else %>
  <p>Login non effettuato. <%= link_to 'Home', root_path %> </p>
<% end %>

app/views/users/informazioni_profilo.html.erb
<% provide :title, 'Informazioni profilo' %>

<% if signed_in? %>

  <div class="row">

    <div class="span4">
      <aside>
        <%= render 'shared/user_info_small' %>
      </aside>
      <%=  render 'users/menu_profilo' %>
    </div>

    <div class="span7 anteprimainformazioni">
      <h3 class="nome center">Informazioni di <%= current_user.name %></h3>

      <div>

        <p>Nickname: <%= current_user.name %></p>
        <p>Email: <%= current_user.email %></p>

        <% if !current_user.birthday.nil? %>
          <p>Compleanno: <%= current_user.birthday.strftime('%d - %m - %Y') %></p>
        <% end %>

        <% if !current_user.city.to_s.empty? %>
          <p>Abiti a: <%= current_user.city %></p>
        <% end %>

        <% if !current_user.em_situation.to_s.empty? %>
          <p>Situazione sentimentale: <%= current_user.em_situation %></p>
        <% end %>

        <% if !current_user.employment.to_s.empty? %>
          <p>Lavoro: <%= current_user.employment %></p>
        <% end %>

        <p>Numero di figli: <%= current_user.n_children %></p>

        <% if !current_user.description.to_s.empty? %>
          <p>Descrizione: <%= current_user.description %></p>
        <% end %>

        <%= render 'children/children' %>

      </div>
    </div>
  </div>

<% else %>
  <p>Login non effettuato. <%= link_to 'Home', root_path %> </p>
<% end %>

app/views/users/new.html.erb
<% provide :title, 'Registrazione' %>

<h1>Registrazione</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= render 'shared/error_messages', object:f.object %>

      <%= f.label :name, 'Nome *' %>
      <%= f.text_field :name %>

      <%= f.label :email, 'Email *'%>
      <%= f.text_field :email %>

      <%= f.label :password, 'Password *' %>
      <%= f.password_field :password%>

      <%= f.label :password_confirmation, 'Conferma password *' %>
      <%= f.password_field :password_confirmation %>

      <%= f.label :n_children, 'N° figli *' %>
      <%= f.text_field :n_children %>

      <div>I campi contrassegnati dall'astrisco (*) sono obbligatori</div>
      <br/>
      <div class="offset1"> <%= link_to 'Annulla', root_path, role: 'button', class: 'btn btn-info'  %>
        <%= f.submit 'Crea il mio account', class: 'btn btn-info' %>
      </div>
    <% end %>
  </div>
</div>






app/views/users/search.html.erb
<% provide :title, 'Risultati ricerca' %>

<% if signed_in? %>

  <h1><%= page_entries_info @users %></h1>

  <ul class="users">
    <%= render @users %>
  </ul>

  <%= will_paginate %>

<% else %>
  <p>Login non effettuato. <%= link_to 'Home', root_path %> </p>
<% end %>

app/views/users/show.html.erb
<% provide :title, @user.name %>

<% if signed_in? %>

  <% #Controllo se l'utente è quello di cui è aperta la sessione o no %>
  <% if @user.id == current_user.id %>

    <%#l'utente di cui sto guardando il profilo è quello che ha effettuato il login %>
    <div class="row" xmlns="http://www.w3.org/1999/html">
      <div class="span4">

        <aside>
          <%= render 'shared/user_info_small' %>
        </aside>

        <%=  render 'users/menu_profilo' %>

      </div>

      <div class="span8">

        <% if current_user.posts.any? %>
          <h3>Miei sfoghi (<%= @user.posts.count %>)</h3>
          <ol class="posts">
            <%= render @posts %>
          </ol>
          <%= will_paginate @posts %>
        <% end %>


        <% if current_user.questions.any? %>
          <h3>Mie domande (<%= @user.questions.count %>)</h3>
          <ol class="posts">
            <%= render "shared/query" %>
          </ol>
          <%= will_paginate @query_items%>
        <% end %>

        <% if @answer_items.any? %>
          <h3>Mie risposte (<%= @answer_items.count %>) </h3>
          <%=  render 'shared/answer' %>
          <%= will_paginate @answer_items%>
        <% end %>

      </div>
    </div>

<% else %>

  <% #L'utente NON è la persona loggata, può essere un utente del sito, un suo follower o following --> possibilità di cambiare formattazione %>
  <% #No possibilità di: modificare il profilo, vedere il menù friends-informazioni-azioni %>
  <div class="row">
    <aside class="span4">

      <section>
        <%= gravatar_for @user, size: 100 %>
        <h1><%= @user.name %></h1>
        <span><%= link_to 'Profilo', @user %></span>
        <span><b>Posts:</b> <%= @user.posts.count %></span>
      </section>

      <section>
        <%= render 'shared/stats' %>
      </section>

      <% if current_user.following?(@user) %>
        <section>
          <%= link_to 'Nuovo messaggio', new_message_path(user: @user.id), role: 'button', class: 'btn btn-info', remote: true %>
        </section>
      <% end %>
    </aside>

    <div class="span8">
      <%=  render 'follow_form' if signed_in? %>

      <% if @user.posts.any? %>
        <h3>Sfoghi (<%= @user.posts.count %>)</h3>
        <ol class="posts">
          <%= render @posts %>
        </ol>
        <%= will_paginate @posts %>
      <% end %>

      <% if @user.questions.any? %>
          <br/>
          <h3>Mie domande (<%= @user.questions.count %>)</h3>
          <ol class="posts">
            <%= render "shared/query" %>
          </ol>
          <%= will_paginate @query_items%>
      <% end %>

      <% if @user.answers.any? %>
          <br/>
          <h3>Mie risposte (<%= @user.answers.count %>) </h3>
          <%=  render 'shared/answer' %>
          <%= will_paginate @answer_items%>
      <% end %>
    </div>
  </div>
<% end %>

<% else %>
    <p>Login non effettuato. <%= link_to 'Home', root_path %> </p>
<% end %>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>

<% if signed_in? %>

  <div class="row">
    <aside class="span4">
      <section>
        <%= gravatar_for @user %>
        <h1 class="nome"><%= @user.name %></h1>

        <span><%= link_to 'Profilo', @user %></span>
        <span><b>Posts:</b> <%= @user.posts.count %></span>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
    </aside>

    <div class="span8">
      <h3><%= @title %></h3>
      <% if @users.any? %>
        <ul class="users">
          <%= render @users %>
        </ul>
        <%= will_paginate %>
      <% end %>
    </div>
  </div>

<% else %>
  <p>Login non effettuato. <%= link_to 'Home', root_path %> </p>
<% end %>