config/routes.rb
Newdad::Application.routes.draw do

  root :to => 'sessions#new'

  match '/about', to: 'pages#about'
  match '/contact', to: 'pages#contact'
  match '/signup', to: 'users#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/eventi', to: 'pages#eventi'
  match '/muro_sfogo', to: 'pages#wall_outburst'

  resources :users do
    member do
      get :following, :followers, :messages, :friends, :my_questions, :informazioni_profilo
    end

    collection do
      get :search
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :messages, only: [:new, :create, :destroy]

  resources :questions do

    collection do
      get :home, :search
    end
  end

  resources :like_questions, only: [:create, :destroy]
  resources :categories
  resources :answers, only: [:create, :destroy]
  resources :age_groups, only: [:show]
  resources :like_answers, only: [:create, :destroy]

end

app/views/shared/_answer_item.html.erb

<li id="<%= answer_item.id %>">
  <%= link_to gravatar_for(answer_item.user), answer_item.user %>

  <span class="user">
   <p class="nome">  <%= link_to answer_item.user.name, answer_item.user %> </p>
  </span>

  <span class="content">Ha risposto: <%= answer_item.content %></span>

  <p>Alla domanda <%= link_to question(answer_item).title, question(answer_item) %> di <%= link_to user(answer_item).name, user(answer_item) %></p>

  <span class="timestamp">
    Risposta creata <%= time_ago_in_words(answer_item.created_at) %> fa
  </span>
</li>

app/views/shared/_category.html.erb
<li class="posts">
  <p class="nome"><%= category.user.name %> ha inserito la categoria: </p>
  <p><%= category.title %></p>

  <%= link_to 'Accetta', edit_category_path(category), role: 'button' %>
  <%= link_to 'Cancella', category, role: 'button', method: :delete, data: {confirm: 'Sei sicuro?'}%>
</li>

app/views/shared/_feed.html.erb

<% if @feed_items.any? %>
  <ol class="posts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb

<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
   <p class="nome"> <%= link_to feed_item.user.name, feed_item.user %>  </p>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Post creato <%= time_ago_in_words(feed_item.created_at) %> fa
  </span>
</li>

app/views/shared/_list_category_to_accept.html.erb

<div class="navbar-inner-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">

      <% if @category.any? %>
        <%= render partial: 'shared/category', collection: @category %>
      <% end %>

    </div>
  </div>
</div>

app/views/shared/_message_form.html.erb

<div id="newMessage" class="modal hide fade">

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h4>A message for <%= @user.name %></h4>
  </div>

  <div class="modal-body">
    <%= form_for(@message) do |f| %>
      <div class="field">
        <%= f.hidden_field :sender, value: current_user.id %>
        <%= f.hidden_field :recipient, value: @user.id %>

        <%= f.label :subject %>
        <%= f.text_field :subject, value: @message.subject %>

        <%= f.label :body %>
        <%= f.text_area :body %>
      </div>

      <div class="modal-footer">
        <%= f.submit 'Invia', class: 'btn btn-info' %>
      </div>

    <% end %>
  </div>
</div>

app/views/shared/_muro.html.erb
<div class="span2">
 <div id="boxA" ondragover="dragOver(event)" ondrop="dragDrop(event)">
   <%=  render 'shared/sfogo' %>
 </div>
   </div>
 <div class="offset2 separatore">
 <table class="tabella" >

   <tr>
     <td>
       <div id="boxB" ondragover="return dragOver(event)" ondrop="dragDrop(event)"></div>
     </td>
     <td>
       <div id="boxC" ondragover="return dragOver(event)" ondrop="dragDrop(event)"></div>
     </td>
     <td>
       <div id="boxD" ondragover="return dragOver(event)" ondrop="dragDrop(event)"></div>
     </td>
     <td>
       <div id="boxI" ondragover="return dragOver(event)" ondrop="dragDrop(event)"></div>
     </td>
   </tr>

   <tr>
     <td>
       <div id="boxE" ondragover="return dragOver(event)" ondrop="dragDrop(event)"></div>
     </td>
     <td>
       <div id="boxF" ondragover="return dragOver(event)" ondrop="dragDrop(event)"></div>
     </td>
     <td>
       <div id="boxG" ondragover="return dragOver(event)" ondrop="dragDrop(event)"></div>
     </td>
     <td>
       <div id="boxH" ondragover="return dragOver(event)" ondrop="dragDrop(event)"></div>
     </td>
   </tr>

   <tr>
     <td>
       <div id="boxL" ondragover="return dragOver(event)" ondrop="dragDrop(event)"></div>
     </td>
     <td>
       <div id="boxM" ondragover="return dragOver(event)" ondrop="dragDrop(event)"></div>
     </td>
     <td>
       <div id="boxN" ondragover="return dragOver(event)" ondrop="dragDrop(event)"></div>
     </td>
     <td>
       <div id="boxO" ondragover="return dragOver(event)" ondrop="dragDrop(event)"></div>
     </td>
   </tr>

   <tr>
     <td>
       <div id="boxP" ondragover="return dragOver(event)" ondrop="dragDrop(event)"></div>
     </td>
     <td>
       <div id="boxQ" ondragover="return dragOver(event)" ondrop="dragDrop(event)"></div>
     </td>
     <td>
       <div id="boxR" ondragover="return dragOver(event)" ondrop="dragDrop(event)"></div>
     </td>
     <td>
       <div id="boxS" ondragover="return dragOver(event)" ondrop="dragDrop(event)"></div>
     </td>
   </tr>

 </table>
</div>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <div class="muro">
    <div class="row">

      <div class="field span6">
        <%= f.text_area :content, placeholder: 'Cosa stai facendo?' %>
      </div>

      <div class="span2"> <br/>
        <%= f.submit 'Post', class: 'btn btn-info' %>
      </div>

      <div class="span4">
        <h3><%= Date.current.strftime('%d / %m / %Y') %></h3>
      </div>
    </div>

    <div class="row">
      <%= render 'shared/muro', object: f.object %>
    </div>

  </div>
<% end %>


app/views/shared/_query.html.erb
<% if @query_items.any? %>
  <ol class="posts">
    <%= render partial: 'shared/query_item', collection: @query_items %>
  </ol>
<% end %>

app/views/shared/_query_item.html.erb
<li id="<%= query_item.id %>">

  <%= link_to gravatar_for(query_item.user), query_item.user %>

  <span class="user">
   <p class="nome"><%= link_to query_item.user.name, query_item.user %>  </p>
  </span>

  <span class="content"><%= link_to query_item.title, query_item %></span>
  <span class="timestamp">
    Domanda creata <%= time_ago_in_words(query_item.created_at) %> fa
  </span>

</li>

app/views/shared/_sfogo.html.erb
<% if @sfogo_items.any? %>

  <ol class="posts">
    <%= render partial: 'shared/sfogo_item', collection: @sfogo_items %>
  </ol>
  <%= will_paginate @sfogo_items %>

<% end %>

app/views/shared/_sfogo_item.html.erb

<div id="<%= sfogo_item.id %>" class="word" draggable="true" ondragstart="return dragDefine(event)" ondragend="dragEnd(event)">
  <p class="user">
    <p class="nome1"><%= link_to sfogo_item.user.name, sfogo_item.user %></p>
  </p>

  <p><%= sfogo_item.content %></p>

  <% if sfogo_item.user_id== current_user.id %>
    <%= link_to 'Cancella', sfogo_item, method: :delete, class:'btn btn-info btn-mini', data: {confirm: 'Sei sicuro?'} %>
  <% end %>

</div>

app/views/shared/_stats.html.erb

<% @user ||= current_user %>
<div class="stats">

  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    Following
  </a>

  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    Followers
  </a>

  <% if current_user?(@user) %>
    <a href="<%= messages_user_path(@user) %>">
      <strong id="unread_messages" class="stat">
        <%= @user.unread_message_count %>
      </strong>
      Messaggi
    </a>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 100 %>
</a>

<h1 class="nome"><%= current_user.name %></h1>
<span class="modifica"><%= link_to 'Modifica Profilo', edit_user_path(current_user) %></span>